version: "3"
services: 
  nginx: 
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
  node-app:
    build: .
    image: shaujie/node-app
    environment:
      - PORT=3000
    depends_on:
      - mongo 
    networks:
      - app-network
      
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shau
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db
    networks:
      - app-network

  redis:
    image: redis
    networks:
      - app-network
    
volumes:
  mongo-db:
  
networks:
  app-network:
    driver: overlay