version: "3"
services: 
  nginx: 
    ports:
      - "80:80"
  node-app:
    deploy:
      replicas: 8
      restart_policy: 
        condition: any # restart for any reason the server goes down
      update_config:
        parallelism: 2 # number of containers to update at a time
        delay: 15s # time to wait between updating a group of containers
    build: 
      context: . # the location of the docker file
      args: 
        NODE_ENV: production 
    environment:
      - NODE_ENV=production
      - MONGO_USER #=${MONGO_USER}
      - MONGO_PASSWORD #=${MONGO_PASSWORD} # to assign the env var in linux terminal => export SESSION_SECRET="secret"
      - SESSION_SECRET #=${SESSION_SECRET} # use linux terminal to store the env => vi.env    , :wq (to save & exit), ls -la & cat .env, i saved in /home/sj/docker_youtube
    command: node index.js
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME #=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD #=${MONGO_INITDB_ROOT_PASSWORD}